<h2> Python Basics

I. Cobalah print kalimat "Hello, my name is ***nama anda***" dengan minimal 2 cara: <br>
a.   Print biasa (nama diletakkan langsung dalam string yang di print)<br>
b.  Menggunakan variabel (nama disimpan dulu di variabel)<br>
c.  Menggunakan operator dan variabel<br>
d.  Menggunakan .format()

In [2]:
# prompt: I. Cobalah print kalimat "Hello, my name is nama anda" dengan minimal 2 cara:
# a. Print biasa (nama diletakkan langsung dalam string yang di print)
# b. Menggunakan variabel (nama disimpan dulu di variabel)
# c. Menggunakan operator dan variabel
# d. Menggunakan .format()

# a. Print biasa
print("Hello, my name is [Stanley]")

# b. Menggunakan variabel
nama = "[Stanley]"
print("Hello, my name is " + nama)

# c. Menggunakan operator dan variabel
nama = "[Stanley]"
print(f"Hello, my name is {nama}")

# d. Menggunakan .format()
nama = "[Stanley]"
print("Hello, my name is {}".format(nama))

Hello, my name is [Stanley]
Hello, my name is [Stanley]
Hello, my name is [Stanley]
Hello, my name is [Stanley]

II. Selesaikan soal cerita berikut menggunakan python:<br>
a.  Jose membeli 4 kotak kelereng, tiap kotak berisi 15 buah kelereng. Kelereng itu akan dibagikan kepada 12 orang temannya, setiap teman akan mendapat ... kelereng.<br>
b.  Hasil dari 8 pangkat 1/3 adalah ...<br>
c.  Eillen memiliki uang sebesar Rp 50.000 untuk dibelanjakan kertas binder, 1 paket kertas binder isi 100 lembar dijual seharga 7500, jika ia ingin membeli berapa kertas binder yang dapat ia beli dengan uang yang ia punya? Berapa kembalian yang diterima?

In [3]:
# prompt: II. Selesaikan soal cerita berikut menggunakan python:
# a. Jose membeli 4 kotak kelereng, tiap kotak berisi 15 buah kelereng. Kelereng itu akan dibagikan kepada 12 orang temannya, setiap teman akan mendapat ... kelereng.
# b. Hasil dari 8 pangkat 1/3 adalah ...
# c. Eillen memiliki uang sebesar Rp 50.000 untuk dibelanjakan kertas binder, 1 paket kertas binder isi 100 lembar dijual seharga 7500, jika ia

# a. Jose membeli 4 kotak kelereng, tiap kotak berisi 15 buah kelereng. Kelereng itu akan dibagikan kepada 12 orang temannya, setiap teman akan mendapat ... kelereng.
jumlah_kotak = 4
kelereng_per_kotak = 15
jumlah_teman = 12

total_kelereng = jumlah_kotak * kelereng_per_kotak
kelereng_per_teman = total_kelereng // jumlah_teman

print("Setiap teman akan mendapat", kelereng_per_teman, "kelereng.")


# b. Hasil dari 8 pangkat 1/3 adalah ...
hasil = 8 ** (1/3)
print("Hasil dari 8 pangkat 1/3 adalah", hasil)


# c. Eillen memiliki uang sebesar Rp 50.000 untuk dibelanjakan kertas binder, 1 paket kertas binder isi 100 lembar dijual seharga 7500, jika ia ingin membeli berapa kertas binder yang dapat ia beli dengan uang yang ia punya? Berapa kembalian yang diterima?
uang_eillen = 50000
harga_paket = 7500

jumlah_paket = uang_eillen // harga_paket
kembalian = uang_eillen % harga_paket

print("Eillen dapat membeli", jumlah_paket, "paket kertas binder.")
print("Kembalian yang diterima adalah Rp", kembalian)

Setiap teman akan mendapat 5 kelereng.
Hasil dari 8 pangkat 1/3 adalah 2.0
Eillen dapat membeli 6 paket kertas binder.
Kembalian yang diterima adalah Rp 5000

III. Tunjukan cara untuk mengonversi tipe-tipe data berikut:

1. "1000" -> 1000 (string ke int)
2. 5.25 -> 5 (float ke int)
3. 5 -> 5.0 (int ke float)
4. 1000 -> "1000" (int ke string)

Expected output:


![image.png]()

In [4]:
# prompt: III. Tunjukan cara untuk mengonversi tipe-tipe data berikut:
# "1000" -> 1000 (string ke int)
# 5.25 -> 5 (float ke int)
# 5 -> 5.0 (int ke float)
# 1000 -> "1000" (int ke string)
# Expected output:
# image.png

# 1. "1000" -> 1000 (string ke int)
string_number = "1000"
int_number = int(string_number)
print(int_number)

# 2. 5.25 -> 5 (float ke int)
float_number = 5.25
int_number = int(float_number)
print(int_number)

# 3. 5 -> 5.0 (int ke float)
int_number = 5
float_number = float(int_number)
print(float_number)

# 4. 1000 -> "1000" (int ke string)
int_number = 1000
string_number = str(int_number)
print(string_number)

1000
5
5.0
1000

IV. String

"If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals."

1. Tampilkan indeks ke 20 sampai 30 dari string di atas (indeks ke 30 ikut)
2. Bagaimana cara memisah string berdasarkan spasi (simpan dalam list)
3. Balik string di atas dengan menggunakan satu baris kode (menggunakan index)

In [5]:
# prompt: "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals."
# Tampilkan indeks ke 20 sampai 30 dari string di atas (indeks ke 30 ikut)
# Bagaimana cara memisah string berdasarkan spasi (simpan dalam list)
# Balik string di atas dengan menggunakan satu baris kode (menggunakan index)

text = "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals."

# 1. Tampilkan indeks ke 20 sampai 30 dari string di atas (indeks ke 30 ikut)
print(text[20:31])

# 2. Bagaimana cara memisah string berdasarkan spasi (simpan dalam list)
word_list = text.split()
print(word_list)

# 3. Balik string di atas dengan menggunakan satu baris kode (menggunakan index)
reversed_text = text[::-1]
print(reversed_text)

what a man'
['If', 'you', 'want', 'to', 'know', 'what', 'a', "man's", 'like,', 'take', 'a', 'good', 'look', 'at', 'how', 'he', 'treats', 'his', 'inferiors,', 'not', 'his', 'equals.']
.slauqe sih ton ,sroirefni sih staert eh woh ta kool doog a ekat ,ekil s'nam a tahw wonk ot tnaw uoy fI

<h2> Python Data Strcutures

I. Tuple


1.   Buatlah sebuah tuple yang berisikan nama prodi di UC, simpan dalam variabel "Prodi".
2.   Cetaklah panjang tuple yang dibuat.
3.   Gunakan .index() untuk mengetahui posisi/index prodi ISB

In [6]:
# prompt: Buatlah sebuah tuple yang berisikan nama prodi di UC, simpan dalam variabel "Prodi".
# Cetaklah panjang tuple yang dibuat.
# Gunakan .index() untuk mengetahui posisi/index prodi ISB

# 1. Buatlah sebuah tuple yang berisikan nama prodi di UC, simpan dalam variabel "Prodi".
Prodi = ("Informatika", "Sistem Informasi", "Teknik Industri", "Desain Komunikasi Visual", "Ilmu Komunikasi", "Akuntansi", "Manajemen", "Ilmu Ekonomi", "Ilmu Hukum", "Psikologi")

# 2. Cetaklah panjang tuple yang dibuat.
print(len(Prodi))

# 3. Gunakan .index() untuk mengetahui posisi/index prodi ISB
print(Prodi.index("Sistem Informasi"))

10
1

II. List


1.   Buatlah sebuah list berisi 3 nama makanan kesukaanmu. Simpan dalam variabel "favorit".
2.   Cetak nama setiap makanan dengan mengakses setiap elemen dalam list satu persatu.
3. Kamu sedang berada di sebuah restoran dan hendak memesan salah satu menu yang ada dalam daftar favoritmu. Cetak setiap makanan dengan contoh: "Aku ingin pesan {nama makanan}"
4.   Ternyata, salah satu menu tidak tersedia, jadi kamu perlu memesan makanan lain. Ganti makanan yang kosong dengan nama makanan baru (makanan yang mana bebas)

In [7]:
# Membuat list makanan kesukaan
favorit = ["Nasi Goreng", "Sushi", "Pizza"]

# Mencetak nama setiap makanan satu per satu
for makanan in favorit:
    print(makanan)

# Memesan makanan dari daftar favorit
for makanan in favorit:
    print(f"Aku ingin pesan {makanan}")

# Mengganti makanan yang tidak tersedia
favorit[1] = "Taco"  # Mengganti Sushi dengan Taco

# Mencetak ulang pesanan setelah penggantian
print("\nSetelah mengganti menu yang tidak tersedia:")
for makanan in favorit:
    print(f"Aku ingin pesan {makanan}")

Nasi Goreng
Sushi
Pizza
Aku ingin pesan Nasi Goreng
Aku ingin pesan Sushi
Aku ingin pesan Pizza

Setelah mengganti menu yang tidak tersedia:
Aku ingin pesan Nasi Goreng
Aku ingin pesan Taco
Aku ingin pesan Pizza

III. Set

1. Buatlah 4 buah set sebagai berikut


    set1 = {1, 2, 3, 4}
    set2 = {2, 4, 6, 8}
    set3 = {5, 7}
    set4 = {2, 3}
2. Gabungkan set1 dan set2 dengan menghilangkan duplicates
3. Buktikan set1 dan set3 tidak mempunyai intersection (output : Boolean)
4. Buktikan set4 adalah bagian dari set1 (output : Boolean)

In [8]:
# Membuat set
set1 = {1, 2, 3, 4}
set2 = {2, 4, 6, 8}
set3 = {5, 7}
set4 = {2, 3}

# Menggabungkan set1 dan set2 dengan menghilangkan duplicates
gabungan = set1.union(set2)
print("Gabungan set1 dan set2:", gabungan)

# Memeriksa apakah set1 dan set3 tidak mempunyai intersection
intersection_check = not set1.intersection(set3)
print("Set1 dan set3 tidak mempunyai intersection:", intersection_check)

# Memeriksa apakah set4 adalah bagian dari set1
subset_check = set4.issubset(set1)
print("Set4 adalah bagian dari set1:", subset_check)

Gabungan set1 dan set2: {1, 2, 3, 4, 6, 8}
Set1 dan set3 tidak mempunyai intersection: True
Set4 adalah bagian dari set1: True

<h2> Python Programming Fundamentals

I. Buatlah sebuah program sederhana yang meminta inputan dari user berupa jumlah penggunaan listrik dan menghasilkan output berupa tarif yang harus dibayar dengan syarat sebagai berikut:

PLN menerapkan pembayaran listrik perumahan dengan perhitungan sebagai berikut:
* untuk golongan 1 (penggunaan <1000 kWh) tarif : Rp1000/kWh
* untuk golongan 2 (penggunaan >= 1000 kWh) tarif : Rp2000/kWh

Dengan syarat perhitungan:

Minimum pembayaran adalah 100 kWh sedangkan untuk pemakaian 1000 kWh dan seterusnya tarifnya ditambah 10% dari total pembayaran.

(Jika total penggunaan <100 kWh, maka akan dikenakan tarif 100 kWh)

In [9]:
# Meminta inputan dari user
penggunaan = float(input("Masukkan jumlah penggunaan listrik (dalam kWh): "))

# Memastikan penggunaan minimal 100 kWh
if penggunaan < 100:
    penggunaan = 100

# Menghitung tarif berdasarkan golongan
if penggunaan < 1000:
    tarif_per_kWh = 1000
else:
    tarif_per_kWh = 2000

# Menghitung total pembayaran
total_pembayaran = penggunaan * tarif_per_kWh

# Menambahkan 10% jika penggunaan >= 1000 kWh
if penggunaan >= 1000:
    total_pembayaran += total_pembayaran * 0.1

# Menampilkan hasil
print(f"Jumlah penggunaan: {penggunaan} kWh")
print(f"Tarif yang harus dibayar: Rp{total_pembayaran:.2f}")

Masukkan jumlah penggunaan listrik (dalam kWh): 200
Jumlah penggunaan: 200.0 kWh
Tarif yang harus dibayar: Rp200000.00

II. Untuk Abdimas Oweek UC digunakan angkot dengan kapasitas 10 orang per angkot. Apabila terjadi kelebihan penumpang (walau hanya 1 orang), angkot yang digunakan ditambah 1. Tulislah program untuk menghitung jumlah angkot yang diperlukan bila jumlah pesertanya menggunakan input().

Catatan, pastikan jika angka yang dimasukkan negatif, muncul peringatan "Jumlah orang tidak bisa negatif!"

In [10]:
# Meminta input jumlah peserta
jumlah_peserta = int(input("Masukkan jumlah peserta: "))

# Memeriksa apakah jumlah peserta negatif
if jumlah_peserta < 0:
    print("Jumlah orang tidak bisa negatif!")
else:
    # Menghitung jumlah angkot yang diperlukan
    kapasitas_angkot = 10
    jumlah_angkot = (jumlah_peserta // kapasitas_angkot) + (1 if jumlah_peserta % kapasitas_angkot > 0 else 0)

    # Menampilkan hasil
    print(f"Jumlah angkot yang diperlukan: {jumlah_angkot}")

Masukkan jumlah peserta: 11
Jumlah angkot yang diperlukan: 2

<h2> Numpy

1. Buatlah 1D numpy array berisi nama nama hari dalam satu minggu
2. Gunakan sort untuk mengurutkan array sesuai abjad
3. Gunakan rand untuk mengambil 1 hari dari array, cetakhlah dalam format: "Selamat hari \<nama hari\> adalah hari baikmu bulan ini!"
4. Buatlah matriks 3x4 menggunakan numpy array berisi angka 1-6, lalu cetak shape dan dimensi array
5. Cetaklah elemen kolom ketiga dari matrix

    [[1 ,2, 3, 4],

    [5, 6, 7, 8],

    [9, 10, 11, 12]]
6. Gunakan reshape untuk mengubah matrix di atas menjadi matriks berukuran (2, 6)

In [24]:
import numpy as np
# Membuat 1D numpy array berisi nama-nama hari dalam satu minggu
hari = np.array(["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"])
print(hari)

['Senin' 'Selasa' 'Rabu' 'Kamis' 'Jumat' 'Sabtu' 'Minggu']

In [22]:
# Membuat 1D numpy array berisi nama-nama hari dalam satu minggu
hari = np.array(["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"])

# Mengurutkan array sesuai abjad
hari.sort()

# Menampilkan hasil
print("Nama-nama hari yang diurutkan:")
print(hari)

Nama-nama hari yang diurutkan:
['Jumat' 'Kamis' 'Minggu' 'Rabu' 'Sabtu' 'Selasa' 'Senin']

In [25]:
import random
# 3
import numpy as np

# Membuat 1D numpy array berisi nama-nama hari dalam satu minggu
hari = np.array(["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"])

# Mengurutkan array sesuai abjad
hari.sort()

# Mengambil 1 hari secara acak
hari_acak = np.random.choice(hari)

# Mencetak pesan
print(f"Selamat hari {hari_acak} adalah hari baikmu bulan ini!")

Selamat hari Jumat adalah hari baikmu bulan ini!

In [26]:
# 4. Membuat matriks 3x4 menggunakan numpy array berisi angka 1-6
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Mencetak shape dan dimensi array
print("Shape matriks:", matrix.shape)
print("Dimensi matriks:", matrix.ndim)

Shape matriks: (3, 4)
Dimensi matriks: 2

In [27]:
# 5 Mencetak elemen kolom ketiga dari matriks
kolom_ketiga = matrix[:, 2]
print("Elemen kolom ketiga:", kolom_ketiga)

Elemen kolom ketiga: [ 3  7 11]

In [28]:
# 6 Mengubah matriks menjadi ukuran (2, 6)
matrix_reshape = matrix.reshape(2, 6)
print("Matriks setelah reshape (2, 6):")
print(matrix_reshape)

Matriks setelah reshape (2, 6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

<h2> Pandas

1. Buatlah Pandas Series dari list ["Information", "Systems", "for", "Business"]
2. Buatlah Pandas Dataframe dari dictionary
{ "brand": "Ford", "model": "Mustang", "year": 1964 }

In [29]:
import pandas as pd

# 1. Membuat Pandas Series dari list
data_list = ["Information", "Systems", "for", "Business"]
series = pd.Series(data_list)

# Menampilkan Series
print("Pandas Series:")
print(series)

# 2. Membuat Pandas DataFrame dari dictionary
data_dict = { "brand": "Ford", "model": "Mustang", "year": 1964 }
dataframe = pd.DataFrame([data_dict])  # Menggunakan list untuk membuat DataFrame

# Menampilkan DataFrame
print("\nPandas DataFrame:")
print(dataframe)

Pandas Series:
0    Information
1        Systems
2            for
3       Business
dtype: object

Pandas DataFrame:
  brand    model  year
0  Ford  Mustang  1964

3. Import dataset berikut kedalam dataframe.    
dataset : https://raw.githubusercontent.com/michellechandraa/TutorDataMining/main/50_Startups.csv
4. Tunjukan kota apa saja yang ada dalam dataset tersebut
5. Buatlah dataset baru yang menyimpan 10 row random dari dataset. Kemudian tunjukanlah 5 row pertamanya.
6. Gunakan df.info() untuk melihat informasi singkat dari dataframe
7. Tampilkan data 'R&D Spend' dan 'Marketing Spend' dari data yang berasal dari kota 'California'
8. Temukan apa ada missing value dari setiap kolom
9. Drop data yang memiliki profit di bawah 50000
10. Urutkan Dataframe berdasarkan biaya marketing mulai dari terbesar ke terkecil

In [36]:
# 3
import pandas as pd
url = "https://raw.githubusercontent.com/michellechandraa/TutorDataMining/main/50_Startups.csv"
df = pd.read_csv(url)
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [42]:
# 4
unique_cities = df['State'].unique()
print("Kota yang ada dalam dataset:", unique_cities)

Kota yang ada dalam dataset: ['New York' 'California' 'Florida']

In [45]:
# 5
random_df = df.sample(n=5, random_state=1)
print("5 row random dari dataset:")
print(random_df)

5 row random dari dataset:
    R&D Spend  Administration  Marketing Spend       State     Profit
27   72107.60       127864.55        353183.81    New York  105008.31
35   46014.02        85047.44        205517.64    New York   96479.51
40   28754.33       118546.05        172795.67  California   78239.91
38   20229.59        65947.93        185265.10    New York   81229.06
2   153441.51       101145.55        407934.54     Florida  191050.39

In [41]:
# 6
print("\nInformasi DataFrame:")
df.info()

Informasi DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [55]:
# 7
df_california_spends = df[df['State'] == 'California'][['R&D Spend', 'Marketing Spend']]
df_california_spends.head()

    R&D Spend  Marketing Spend
1   162597.70        443898.53
6   134615.46        127716.82
9   123334.88        304981.62
11  100671.96        249744.55
13   91992.39        252664.93

In [50]:
# 8
missing_values = df.isnull().sum()
print("Missing values per kolom:\n", missing_values)

Missing values per kolom:
 R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [53]:
# 9
df_filtered = df[df['Profit'] >= 50000]
df_filtered.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [56]:
# 10
df_sorted = df_filtered.sort_values(by='Marketing Spend', ascending=False)
df_sorted.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

<h2> Data Cleaning

1. Import dataset berikut ke dalam dataframe.   
   dataset : https://raw.githubusercontent.com/michellechandraa/TutorDataMining/main/real_estate.csv
2. Tampilkan 10 data random dari dataset di atas
3. Cari informasi data dengan menggunakan fungsi describe
4. Hapus kolom 'No' dan ubahlah nama kolom dalam dataframe menjadi 'transaction date', 'house age', 'distance to the nearest MRT station', 'number of convinience stores', 'latitude', 'longitude', 'house price of unit area'
5. Cek apakah ada missing values dari masing-masing kolom

In [70]:
# 1
url = "https://raw.githubusercontent.com/michellechandraa/TutorDataMining/main/real_estate.csv"
df = pd.read_csv(url)
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [71]:
# 2
df_random_data = df.sample(n=10, random_state=1)
df_random_data.head(10)

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
388,389,2013.500,10.4,2251.9380,4,24.95957,121.51353,27.3
102,103,2013.083,1.1,193.5845,6,24.96571,121.54089,54.4
187,188,2013.000,8.9,3078.1760,0,24.95464,121.56627,22.0
162,163,2012.750,16.0,4066.5870,0,24.94297,121.50342,11.6
90,91,2012.833,0.0,274.0144,1,24.97480,121.53059,45.4
398,399,2013.417,14.7,1717.1930,2,24.96447,121.51649,23.0
295,296,2013.167,18.2,2179.5900,3,24.96299,121.51252,21.8
397,398,2013.417,13.1,1164.8380,4,24.99156,121.53406,32.2
17,18,2012.750,17.7,350.8515,1,24.97544,121.53119,37.4
58,59,2013.500,30.3,4510.3590,1,24.94925,121.49542,22.6

In [72]:
# 3
df_description = df.describe()
df_description.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
count,414.000000,414.000000,414.000000,414.000000,414.000000,414.00000,414.000000,414.000000
mean,207.500000,2013.148971,17.712560,1083.885689,4.094203,24.96903,121.533361,37.980193
std,119.655756,0.281967,11.392485,1262.109595,2.945562,0.01241,0.015347,13.606488
min,1.000000,2012.667000,0.000000,23.382840,0.000000,24.93207,121.473530,7.600000
25%,104.250000,2012.917000,9.025000,289.324800,1.000000,24.96300,121.528085,27.700000

In [73]:
# 4
df = df.drop(columns=['No'])
df.columns = ['transaction date', 'house age', 'distance to the nearest MRT station',
              'number of convenience stores', 'latitude', 'longitude',
              'house price of unit area']
df.head()

,transaction date,house age,distance to the nearest MRT station,number of convenience stores,latitude,longitude,house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [74]:
# 5
df_missing_values = df.isnull().sum()
df_missing_values.head()

transaction date                       0
house age                              0
distance to the nearest MRT station    0
number of convenience stores           0
latitude                               0
dtype: int64

## **Goodluck :)**